import micromatch from "micromatch";

export const EXCLUDED_FILES = [
  ".gitignore",
  "README.md",
  "LICENSE",
  "package.json",
  "package-lock.json",
  "yarn.lock",
  "pnpm-lock.yaml",
  "npm-shrinkwrap.json",
  "Pipfile",
  "Pipfile.lock",
  "requirements.txt",
  "pyproject.toml",
  "pubspec.yaml",
  "pubspec.lock",
  "pom.xml",
  "build.gradle",
  "build.gradle.kts",
  "settings.gradle",
  "settings.gradle.kts",
  "*.csproj",
  "*.sln",
  "Gemfile",
  "Gemfile.lock",
  "Cargo.toml",
  "Cargo.lock",
  "composer.json",
  "composer.lock",
  "go.mod",
  "go.sum",
  "mix.exs",
  "mix.lock",
  "Package.swift",
  "Cartfile",
  "Cartfile.resolved",
  "Podfile",
  "Podfile.lock",
  "gradle-wrapper.properties",
  "tsconfig.json",
  "jsconfig.json",
  ".eslintrc.js",
  ".eslintrc.json",
  ".prettierrc",
  ".prettierrc.json",
  ".babelrc",
  "*.lock",
  "Makefile",
  "Dockerfile",
  "docker-compose.yml",
  "CMakeLists.txt",
  ".env",
  "*.json",
  "*.lock",
  "*.xml",
  "*.yml",
  "*.yaml",
  "*.yml.example",
  "*.yaml.example",
  "*.yml.example",
  "*.yaml.example",

  // iOS and Android folders (React Native, Flutter)
  "ios/**/*",
  "android/**/*",

  // Build folders
  "build/**/*",
  "out/**/*",
  "dist/**/*",

  // node_modules
  "node_modules/**/*",

  // Assets
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.svg",
  "*.mp3",
  "*.mp4",
  "*.wav",
  "*.ogg",
  "*.ttf",
  "*.otf",
  "*.ico",
  "*.webp",
  "*.webm",
];

export const isExcluded = (filePath: string) => {
  return micromatch.isMatch(filePath, EXCLUDED_FILES);
};
